export class Contact {
    "E-mail Address": string = "junecrane@furnitech.com";
    "Related name": string = "";
    "Home Address 2": string = "";
    "Anniversary": string = "";
    "First Name": string = "Stokes";
    "Business Address 2": string = ""
    "Department": string = "";
    "Display Name": string = "Kim Harper";
    "Home State": string = "";
    "Business Country": string = "";
    "Home Street": string = "";
    "Birthday": string = "";
    "Home Country": string = "";
    "Pager": string = "";
    "Categories": string = "";
    "Home City": string = "";
    "E-mail 3 Address": string = "";
    "Home Fax": string = "";
    "Gender": string = "";
    "Notes": string = "eu";
    "Country Code": string = "";
    "Job Title": string = "";
    "Business Address": string = "";
    "Web Page 2": string = "";
    "Mobile Phone": string = "";
    "Organization": string = "";
    "Home Phone": string = "(883) 482-3894";
    "E-mail 2 Address": string = "";
    "Last Name": string = "Hyde";
    "Nickname": string = "";
    "Business Fax": string = "";
    "Home Postal Code": string = "";
    "Business Phone": string = "";
    "Business Postal Code": string = "";
    "Web Page": string = "";
    "Business City": string = "";
    "Business State": string = "";
}